# Generated by Django 5.0.7 on 2026-05-19 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_room_status_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
