# Generated by Django 5.0.7 on 2026-05-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='location',
            new_name='category',
        ),
    ]
